[build]
rustflags = ["-C", "target-feature=+sse,+sse2,+sse3,+sse4.1,+sse4.2,+fma,+avx,+avx2,+aes"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.wasm32-wasi]
rustflags = ["-C", "target-feature=+simd128"]
